name:         hash_compare
version:      0.1.0+3
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  Hash and compare function generator
homepage:     https://github.com/bergwerf/hash-compare
environment:
  sdk:        '>=2.0.0 <3.0.0'

dependencies:
  build:        ^1.1.0
  source_gen:   ^0.9.0
  build_config: ^0.3.1+4
  analyzer:     ^0.32.2

dev_dependencies:
  test: any
  build_runner: any
  english_words: ^3.1.5
