name:         hash_compare
version:      0.1.0+4
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  Hash and compare function generator
homepage:     https://github.com/bergwerf/hash-compare
environment:
  sdk:        '>=2.0.0 <3.0.0'

dependencies:
  build:        ^1.2.2
  source_gen:   ^0.9.4+7
  build_config: ^0.4.1+1
  analyzer:     ^0.39.4

dev_dependencies:
  test: any
  build_runner: any
  english_words: ^3.1.5
